import { StyledEngineProvider, createTheme } from '@mui/material'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const theme = createTheme({
//   components: {
//     MuiPopover: {
//       defaultProps: {
//         container: rootElement,
//       },
//     },
//     MuiPopper: {
//       defaultProps: {
//         container: rootElement,
//       },
//     },
//     MuiDialog: {
//       defaultProps: {
//         container: rootElement,
//       },
//     },
//     MuiModal: {
//       defaultProps: {
//         container: rootElement,
//       },
//     },
//   },
// });

const RootLayout = ({ children }: { children: React.ReactNode}) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledEngineProvider injectFirst>

          {children}
        </StyledEngineProvider>
      </body>
    </html>
  )
}

export default RootLayout;